/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package assignmenttwo;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * This is the generated Hello World Greeting App.
 */
public class App {

  private void sunPlanetMoon() {
    System.out.println("Solar system:\n");
    assignmenttwo.solitares.Star star = new assignmenttwo.solitares.Star("Sun", 696342);
    System.out.println(star.toString());

    assignmenttwo.solitares.Planet[] planets = new assignmenttwo.solitares.Planet[8];
    planets[0] = new assignmenttwo.solitares.Planet("Mercury", 2439);
    planets[1] = new assignmenttwo.solitares.Planet("Venus", 6051);
    planets[2] = new assignmenttwo.solitares.Planet("Earth", 6371);
    planets[3] = new assignmenttwo.solitares.Planet("Mars", 3389);
    planets[4] = new assignmenttwo.solitares.Planet("Jupiter", 69911);
    planets[5] = new assignmenttwo.solitares.Planet("Saturn", 58232);
    planets[6] = new assignmenttwo.solitares.Planet("Uranus", 25362);
    planets[7] = new assignmenttwo.solitares.Planet("Neptune", 10000);

    System.out.println("\nPlanets: ");
    for (assignmenttwo.solitares.Planet planet : planets) {
      System.out.println(planet.toString());
    }

    assignmenttwo.solitares.Moon[] moons = new assignmenttwo.solitares.Moon[8];
    moons[0] = new assignmenttwo.solitares.Moon("Phobos", 22);
    moons[1] = new assignmenttwo.solitares.Moon("Deimos", 12);
    moons[2] = new assignmenttwo.solitares.Moon("Luna", 3475);
    moons[3] = new assignmenttwo.solitares.Moon("Phobos", 11);
    moons[4] = new assignmenttwo.solitares.Moon("Ganymede", 5262);
    moons[5] = new assignmenttwo.solitares.Moon("Titan", 5150);
    moons[6] = new assignmenttwo.solitares.Moon("Titania", 1578);
    moons[7] = new assignmenttwo.solitares.Moon("Triton", 2707);

    System.out.println("\nSome Moons: ");
    for (assignmenttwo.solitares.Moon moon : moons) {
      System.out.println(moon.toString());
    }
  }

  private void heavenlyBody() {

    System.out.println("Solar system:\n");
    assignmenttwo.refactoredsolitares.Star star = new assignmenttwo.refactoredsolitares.Star("Sun", 696342);
    System.out.println(star.toString());

    assignmenttwo.refactoredsolitares.Planet[] planets = new assignmenttwo.refactoredsolitares.Planet[8];
    planets[0] = new assignmenttwo.refactoredsolitares.Planet("Mercury", 2439);
    planets[1] = new assignmenttwo.refactoredsolitares.Planet("Venus", 6051);
    planets[2] = new assignmenttwo.refactoredsolitares.Planet("Earth", 6371);
    planets[3] = new assignmenttwo.refactoredsolitares.Planet("Mars", 3389);
    planets[4] = new assignmenttwo.refactoredsolitares.Planet("Jupiter", 69911);
    planets[5] = new assignmenttwo.refactoredsolitares.Planet("Saturn", 58232);
    planets[6] = new assignmenttwo.refactoredsolitares.Planet("Uranus", 25362);
    planets[7] = new assignmenttwo.refactoredsolitares.Planet("Neptune", 10000);

    System.out.println("\nPlanets: ");
    for (assignmenttwo.refactoredsolitares.Planet planet : planets) {
      System.out.println(planet.toString());
    }

    assignmenttwo.refactoredsolitares.Moon[] moons = new assignmenttwo.refactoredsolitares.Moon[8];
    moons[0] = new assignmenttwo.refactoredsolitares.Moon("Phobos", 22);
    moons[1] = new assignmenttwo.refactoredsolitares.Moon("Deimos", 12);
    moons[2] = new assignmenttwo.refactoredsolitares.Moon("Luna", 3475);
    moons[3] = new assignmenttwo.refactoredsolitares.Moon("Phobos", 11);
    moons[4] = new assignmenttwo.refactoredsolitares.Moon("Ganymede", 5262);
    moons[5] = new assignmenttwo.refactoredsolitares.Moon("Titan", 5150);
    moons[6] = new assignmenttwo.refactoredsolitares.Moon("Titania", 1578);
    moons[7] = new assignmenttwo.refactoredsolitares.Moon("Triton", 2707);

    System.out.println("\nSome Moons: ");
    for (assignmenttwo.refactoredsolitares.Moon moon : moons) {
      System.out.println(moon.toString());
    }
  }

  private void solarSytem() {
    System.out.println("Solar system:\n");
    assignmenttwo.solarsystem.Star star = new assignmenttwo.solarsystem.Star("Sun", 696342);
    star.addPlanet("Earth", 6371, 63710);
    star.addMoon("Moon", "Earth", 1737, 17370);
    star.addPlanet("Mars", 3389, 33890);
    star.addMoon("Phobos", "Mars", 12, 120);
    star.addMoon("Deimos", "Mars", 6, 60);
    star.addPlanet("Jupiter", 69911, 699110);
    star.addMoon("Io", "Jupiter", 1821, 18210);
    star.addMoon("Europa", "Jupiter", 1560, 15600);
    star.addMoon("Ganymede", "Jupiter", 2634, 26340);
    star.addMoon("Callisto", "Jupiter", 2410, 24100);
    star.addPlanet("Saturn", 58232, 582320);
    star.addMoon("Mimas", "Saturn", 198, 1980);
    star.addMoon("Enceladus", "Saturn", 252, 2520);
    star.addMoon("Tethys", "Saturn", 533, 5330);
    star.addMoon("Dione", "Saturn", 561, 5610);
    star.addMoon("Rhea", "Saturn", 764, 7640);
    star.addMoon("Titan", "Saturn", 2575, 25750);

    for (assignmenttwo.solarsystem.HeavenlyBody body : star.getHeavenlyBodies()) {
      System.out.println(body);
    }
  }

  private void orderInHeaven() {
    System.out.println("Solar system:\n");
    assignmenttwo.solarsystem.Star star = new assignmenttwo.solarsystem.Star("Sun", 696342);
    star.addPlanet("Earth", 6371, 63710);
    star.addMoon("Moon", "Earth", 1737, 17370);
    star.addPlanet("Mars", 3389, 33890);
    star.addMoon("Phobos", "Mars", 12, 120);
    star.addMoon("Deimos", "Mars", 6, 60);
    star.addPlanet("Jupiter", 69911, 699110);
    star.addMoon("Io", "Jupiter", 1821, 18210);
    star.addMoon("Europa", "Jupiter", 1560, 15600);
    star.addMoon("Ganymede", "Jupiter", 2634, 26340);
    star.addMoon("Callisto", "Jupiter", 2410, 24100);
    star.addPlanet("Saturn", 58232, 582320);
    star.addMoon("Mimas", "Saturn", 198, 1980);
    star.addMoon("Enceladus", "Saturn", 252, 2520);
    star.addMoon("Tethys", "Saturn", 533, 5330);
    star.addMoon("Dione", "Saturn", 561, 5610);
    star.addMoon("Rhea", "Saturn", 764, 7640);
    star.addMoon("Titan", "Saturn", 2575, 25750);

    assignmenttwo.solarsystem.HeavenlyBody[] heavenlyBodies = star.getHeavenlyBodies();
    List<assignmenttwo.solarsystem.HeavenlyBody> heavenlyBodiesList = Arrays.asList(heavenlyBodies);
    Collections.sort(heavenlyBodiesList);
    // print the sorted ArrayList
    for (assignmenttwo.solarsystem.HeavenlyBody body : heavenlyBodiesList) {
      System.out.println(body);
    }
  }

  /**
   * The App starting point.
   *
   * @param args Unused program arguments.
   */
  public static void main(String[] args) {
    App theApp = new App();
    theApp.sunPlanetMoon();
    theApp.heavenlyBody();
    theApp.solarSytem();
    theApp.orderInHeaven();
  }
}
