/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package assignment4;

/**
 * This program was created by Noa Kron.
 */

public class App {

  /**
   * The App starting point.
   *
   * @param args Unused program arguments.
   */
  public static void main(String[] args) {
    assignment4.solarsystem.ShowMenu menu = new assignment4.solarsystem.ShowMenu();
    menu.menu();
  }

}
