/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package assignmentone;

import java.util.Scanner;

/**
 * This is the main class for the assignment.
 */
public class App {
  private Scanner input;

  private App(Scanner scannerInput) {
    this.input = scannerInput;
  }

  /**
   * Solution to first task.
   */
  public void helloThere() {
    System.out.print("What is your name? ");
    String name = input.nextLine();

    HelloThere ht = new HelloThere();
    System.out.println(ht.hello(name));
  }

  /**
   * Solution for the second task.
   */
  public void seconds() {
    System.out.print("Enter hours, minutes, and seconds separated by spaces: ");
    int hours = input.nextInt();
    int minutes = input.nextInt();
    int seconds = input.nextInt();

    Time t = new Time();
    int totalSeconds = t.toSeconds(hours, minutes, seconds);

    System.out.println("Total seconds: " + totalSeconds);
  }


  /**
   * Solution for the third task.
   */
  public void imInaBand() {
    Album album = new Album("The Dark Side of the Moon", 1973, "Pink Floyd");
    System.out.println(album);

    album.setName("Abbey Road");
    album.setArtist("The Beatles");
    album.setYear(1969);
    System.out.println(album);

    album.setName("a");
    album.setArtist("b");
    album.setYear(2025);
    System.out.println(album);
  }

  /**
   * Solution for the fourth task.
   */
  public void bestAlbumsEver() {
    AlbumGenerator ag = new AlbumGenerator();
    Album[] albums = ag.generateAlbums();

    for (Album album : albums) {
      System.out.println(album.getName() + " was released in " + album.getYear() + " by " + album.getArtist());
    }

  }

  /**
   * Solution for the fifth task.
   */
  public void workingWithArrays() {
    ArrayAlgorithms aa = new ArrayAlgorithms();
    int[] arr = {5, 2, 6, 4, 1, 3, 7, 9, 8};

    System.out.print("Array: ");
    for (int j : arr) {
      System.out.print(j + " ");
    }
    System.out.println();

    System.out.println("Average of array is: " + aa.average(arr));
    System.out.println("Largest value in array is: " + aa.maxValue(arr));
    System.out.println("Index of smallest value is: " + aa.minIndex(arr));

    System.out.print("Shifted array: ");
    int[] shiftedArr = aa.shift(arr);
    for (int j : shiftedArr) {
      System.out.print(j + " ");
    }
    System.out.println();

    System.out.print("Shuffled array: ");
    int[] shuffledArr = aa.shuffle(arr);
    for (int j : shuffledArr) {
      System.out.print(j + " ");
    }
    System.out.println();
  }


  /**
   * Starting point of the first assignment.
   *
   * @param args is not used.
   */
  public static void main(String[] args) {
    

    // we create a scanner object to work with
    // it is advised to create one and only one scanner for a specific stream in the whole application
    // scanners should be closed when you are done and this also closes the underlying stream
    Scanner consoleInput = new Scanner(System.in, "UTF-8");

    App app = new App(consoleInput);

    // Task 1
    app.helloThere();

    // Task 2
    app.seconds();

    // Task 3
    app.imInaBand();

    // Task 4 
    app.bestAlbumsEver();

    // Task 5
    app.workingWithArrays();

    // now we are exiting the application so time to close the scanner.
    consoleInput.close();
  }
}
